### ISSUE TITLE
clearPackageData flag gets ignored

### ISSUE THREAD

**Issue by beworker** [bitrise-steplib/steps-virtual-device-testing-for-android#38]
It relates to #29 

When running instrumentation tests, I need to set `clearPackageData true` flag as [Android documentation](https://developer.android.com/training/testing/junit-runner) says (search for `-e clearPackageData true`).

I tried to put the flag into the following step

```yaml
    - virtual-device-testing-for-android:
        inputs:
        - test_devices: Nexus6,25,de,portrait
        - inst_use_orchestrator: 'true'
        - test_timeout: '100'
        - test_type: instrumentation
```

like this (`inputs:` are omitted for sake of simplicity)
```yaml
    - virtual-device-testing-for-android:
        environment-variables:
           clearPackageData: true
```

like this
```yaml
    - virtual-device-testing-for-android:
        environment-variables:
           clearPackageData: 'true'
```

like this
```yaml
    - virtual-device-testing-for-android:
        environment-variables:
        - clearPackageData: true
```

and like this
```yaml
    - virtual-device-testing-for-android:
        environment-variables:
        - clearPackageData: 'true'
```

In all the cases tests have failed because the flag has not been actually applied.

Is this flag supported and if yes, what would be the correct syntax to provide it to the tests?

**Comment by tir38** [comment]
I just used the UI editor:

<img width="853" alt="screen shot 2019-02-22 at 6 03 42 pm" src="https://user-images.githubusercontent.com/1980553/53278157-9eb35e80-36d5-11e9-92b0-31f5ec812cf2.png">

Which resulting in our `bitrise.yml` updating to:

```
 - virtual-device-testing-for-android:
        inputs:
        - test_devices: "$INSTRUMENTATION_DEVICE_LIST"
        - inst_use_orchestrator: 'true'
        - environment_variables: clearPackageData=true
        - test_type: instrumentation
```

You can see that it got set when you run the workflow:

```
Configs:
- ApkPath: /bitrise/deploy/app-debug.apk
- TestTimeout: 900
- DirectoriesToPull: 
- EnvironmentVariables: clearPackageData=true
- TestDevices:
---
Model     API Level   Locale     Orientation   
Nexus5X   24          portrait   en            
Nexus5X   25          portrait   en            
Nexus5X   26          portrait   en            
Pixel2    27          portrait   en            
---
- AppPackageID: 
- TestType: instrumentation
- TestApkPath: /bitrise/deploy/app-debug-androidTest.apk
- InstTestPackageID: 
- InstTestRunnerClass: 
- InstTestTargets: 
- UseOrchestrator: true
```

All of our tests are now passing.
