### ISSUE TITLE
How to export coverage.ec file

### ISSUE THREAD

**Issue by hernandazevedo** [bitrise-steplib/steps-virtual-device-testing-for-android#58]
I am trying to use the step to export the coverage.ec file as described with no success, the file is not being exported.

What I am doing wrong?

This is my configuration
```
- virtual-device-testing-for-android@1.1.1:
        inputs:
        - environment_variables: |-
            coverage=true
            coverageFile=/sdcard/coverage.ec
        - directories_to_pull: "/sdcard/"
        - download_test_results: 'true'
        - use_verbose_log: 'true'
        - test_type: instrumentation
```

![image](https://user-images.githubusercontent.com/3296199/68319548-3f4b8200-009d-11ea-854d-c1b183c9be47.png)
